version: '3'
services:
  web1:
    image: webpos-image
    deploy:
      resources:
        limits:
          cpus: "0.5"
  web2:
    image: webpos-image
    deploy:
      resources:
        limits:
          cpus: "0.5"
  web3:
    image: webpos-image
    deploy:
      resources:
        limits:
          cpus: "0.5"
  web4:
    image: webpos-image
    deploy:
      resources:
        limits:
          cpus: "0.5"
  main:
    image: haproxy:2.1
    depends_on:
      - web1
      - web2
      - web3
      - web4
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8080:8080"